GLOSSARY = [
    {"term": "AA (Alcoholics Anonymous)", "definition": "An international fellowship of people who share their experience, strength, and hope with each other to recover from alcoholism, using a 12-step program."},
    {"term": "Abstinence", "definition": "The practice of completely avoiding alcohol and other addictive substances."},
    {"term": "Alcohol Use Disorder (AUD)", "definition": "A medical condition characterized by an impaired ability to stop or control alcohol use despite adverse social, occupational, or health consequences."},
    {"term": "ALT (Alanine Aminotransferase)", "definition": "A liver enzyme. Elevated ALT often indicates liver inflammation or damage. Normal range: ~7–56 U/L."},
    {"term": "AST (Aspartate Aminotransferase)", "definition": "A liver enzyme that can also be found in heart and muscles. Elevated AST may indicate liver damage. Normal range: ~10–40 U/L."},
    {"term": "Bilirubin", "definition": "A yellow compound produced by the breakdown of red blood cells. High bilirubin can indicate liver problems or biliary obstruction."},
    {"term": "Cirrhosis", "definition": "Late-stage scarring (fibrosis) of the liver caused by many forms of liver disease and conditions, including chronic alcohol use."},
    {"term": "Craving", "definition": "A strong desire or urge to drink alcohol; a hallmark of alcohol dependence."},
    {"term": "Detoxification (Detox)", "definition": "The process by which the body clears itself of alcohol or drugs. Medical detox may be required for safety when stopping heavy drinking."},
    {"term": "Dehydration", "definition": "A condition that occurs when you lose more fluids than you take in. Alcohol is a diuretic and contributes to dehydration."},
    {"term": "Fatty Liver Disease", "definition": "A condition in which excess fat builds up in the liver. Alcoholic fatty liver disease is one of the earliest stages of alcohol-related liver disease."},
    {"term": "GABA", "definition": "A neurotransmitter affected by alcohol. Long-term drinking dysregulates GABA, contributing to withdrawal symptoms."},
    {"term": "GGT (Gamma-Glutamyl Transferase)", "definition": "A liver enzyme often elevated in alcohol-related liver disease and biliary issues. Normal range: ~9–48 U/L."},
    {"term": "Harm Reduction", "definition": "A set of practical strategies and ideas aimed at reducing negative consequences associated with drug or alcohol use."},
    {"term": "HALT", "definition": "An acronym (Hungry, Angry, Lonely, Tired) used in recovery to identify common triggers that can lead to relapse."},
    {"term": "Hepatitis (Alcoholic)", "definition": "Inflammation of the liver caused by heavy alcohol consumption."},
    {"term": "Kindling", "definition": "A phenomenon in which repeated alcohol withdrawal episodes cause increasingly severe symptoms over time."},
    {"term": "MCV (Mean Corpuscular Volume)", "definition": "Average size of red blood cells. Elevated MCV can be associated with chronic heavy alcohol use."},
    {"term": "Naltrexone", "definition": "A medication used to help reduce alcohol cravings and the rewarding effects of drinking."},
    {"term": "Protein (Dietary)", "definition": "An essential macronutrient that supports liver repair, muscle maintenance, and immune function. Recommended intake for recovery may be elevated (e.g., 140g/day)."},
    {"term": "Relapse", "definition": "A return to alcohol use after a period of abstinence. Often a part of the recovery journey, not a failure."},
    {"term": "SMART Recovery", "definition": "Self-Management And Recovery Training: a science-based recovery program emphasizing self-empowerment and cognitive-behavioral techniques."},
    {"term": "Sobriety", "definition": "The state of not being intoxicated; in recovery contexts, ongoing abstinence from alcohol."},
    {"term": "Sodium / Salt", "definition": "An electrolyte important for fluid balance. Excess sodium can worsen high blood pressure and put strain on a recovering liver. 1g salt ≈ 400mg sodium."},
    {"term": "Sponsor", "definition": "In 12-step programs, an experienced member who guides a newer member through recovery."},
    {"term": "Thiamine (Vitamin B1)", "definition": "A vitamin commonly deficient in heavy drinkers. Supplementation helps prevent Wernicke-Korsakoff syndrome."},
    {"term": "Tolerance", "definition": "A reduced response to alcohol after repeated use, requiring more to achieve the same effect."},
    {"term": "Trigger", "definition": "An emotional, environmental, or social situation that increases the urge to drink."},
    {"term": "Water (Daily Intake)", "definition": "Adequate hydration is critical in recovery. Some recovery plans specifically cap intake (e.g., 1.5L/day) to avoid electrolyte imbalance — follow medical guidance."},
    {"term": "Wernicke-Korsakoff Syndrome", "definition": "A serious brain disorder caused by thiamine deficiency, commonly associated with chronic alcoholism."},
    {"term": "Withdrawal", "definition": "Physical and psychological symptoms experienced when stopping alcohol use after dependency has formed. Can be medically serious."},
]
